services:
  mysql:
    image: mysql:8.0
    container_name: app-sql
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: sgrmanage
      TZ: UTC
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ../SG_Manage_Member_BE/src/database/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql  # Thêm dòng này
    networks:
      - example-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    expose:
      - 3306

  app_server:
    build: 
      context: ../SG_Manage_Member_BE
      dockerfile: Dockerfile
    tty: true
    container_name: app-api
    environment:
      - DB_HOST=mysql
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/www
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - example-network
    expose:
      - 3000
  
  nginx:
    image: nginx:1.25.2
    ports:
      - 80:80
    volumes:
      - ../SG_Manage_Member_FE/dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

networks:
  example-network:
    driver: bridge


# docker compose -p sg_manage_member up -d

